//! Pi loads a TypeScript extension instead of shell-command hook settings.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::output::{Output, display_path};

const EXTENSION: &str = include_str!("pi/extension.ts");
const GENERATED_HEADER: &str = "// Generated by Symposium. Do not edit.\n";

pub(super) fn agent_dir(home: &Path) -> PathBuf {
    match std::env::var_os("PI_CODING_AGENT_DIR").filter(|v| !v.is_empty()) {
        Some(dir) => {
            let path = PathBuf::from(dir);
            match path.strip_prefix("~") {
                Ok(rest) => home.join(rest),
                Err(_) => path,
            }
        }
        None => home.join(".pi").join("agent"),
    }
}

pub(super) fn register_extension(root: &Path, out: &Output) -> Result<()> {
    let path = root.join("extensions").join("symposium.ts");
    if path.exists() {
        let existing = fs::read_to_string(&path)?;
        if existing == EXTENSION {
            out.already_ok(format!(
                "{}: Pi extension already configured",
                display_path(&path)
            ));
            return Ok(());
        }
        if !existing.starts_with(GENERATED_HEADER) {
            bail!(
                "{}: refusing to replace a user-managed Pi extension",
                display_path(&path)
            );
        }
    }
    fs::create_dir_all(path.parent().unwrap())?;
    let temp = path.with_extension(format!("symposium-tmp-{}", std::process::id()));
    fs::write(&temp, EXTENSION).with_context(|| format!("write {}", temp.display()))?;
    if let Err(e) = fs::rename(&temp, &path) {
        let _ = fs::remove_file(&temp);
        return Err(e).with_context(|| format!("replace {}", path.display()));
    }
    out.done(format!("{}: installed Pi extension", display_path(&path)));
    Ok(())
}

pub(super) fn unregister_extension(root: &Path, out: &Output) {
    let path = root.join("extensions").join("symposium.ts");
    let Ok(existing) = fs::read_to_string(&path) else {
        return;
    };
    if !existing.starts_with(GENERATED_HEADER) {
        return;
    }
    match fs::remove_file(&path) {
        Ok(()) => out.done(format!("{}: removed Pi extension", display_path(&path))),
        Err(e) => out.warn(format!(
            "{}: failed to remove Pi extension: {e}",
            display_path(&path)
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extension_registration_is_idempotent_and_removable() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        let path = root.join("extensions/symposium.ts");
        register_extension(root, &Output::quiet()).unwrap();
        let before = fs::metadata(&path).unwrap().modified().unwrap();
        register_extension(root, &Output::quiet()).unwrap();
        assert_eq!(fs::metadata(&path).unwrap().modified().unwrap(), before);
        assert_eq!(fs::read_to_string(&path).unwrap(), EXTENSION);
        unregister_extension(root, &Output::quiet());
        assert!(!path.exists());
    }

    #[test]
    fn user_extension_is_not_overwritten_or_removed() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("extensions/symposium.ts");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, "export default function () {}\n").unwrap();
        assert!(register_extension(tmp.path(), &Output::quiet()).is_err());
        unregister_extension(tmp.path(), &Output::quiet());
        assert_eq!(
            fs::read_to_string(path).unwrap(),
            "export default function () {}\n"
        );
    }

    #[test]
    fn old_generated_extension_is_updated() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("extensions/symposium.ts");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, format!("{GENERATED_HEADER}// old version\n")).unwrap();
        register_extension(tmp.path(), &Output::quiet()).unwrap();
        assert_eq!(fs::read_to_string(path).unwrap(), EXTENSION);
    }
}
