// Generated by Symposium. Do not edit.
// This extension connects Pi events to `cargo-agents hook pi`.
import { execFile } from "node:child_process";
import { existsSync, readdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

interface HookOutput {
  decision?: "allow" | "deny";
  additionalContext?: string;
  updatedInput?: Record<string, unknown>;
}

// Hook commands install tools on demand, including during tool events.
export const DEFAULT_HOOK_TIMEOUT_MS = 10 * 60_000;

export function runHook(
  event: string,
  payload: Record<string, unknown>,
  cwd: string,
  command = "cargo-agents",
  signal?: AbortSignal,
  timeout = DEFAULT_HOOK_TIMEOUT_MS,
): Promise<HookOutput> {
  return new Promise((resolve, reject) => {
    const child = execFile(
      command,
      ["hook", "pi", event],
      { cwd, timeout, maxBuffer: 1024 * 1024, windowsHide: true, signal },
      (error, stdout, stderr) => {
        if (error) {
          const reason = error.killed && error.code == null && !signal?.aborted
            ? `timed out after ${timeout} ms` : stderr.trim() || error.message;
          reject(new Error(`Symposium ${event}: ${reason}`));
          return;
        }
        try {
          const output = stdout.trim() ? JSON.parse(stdout) : {};
          if (!output || typeof output !== "object" || Array.isArray(output)) {
            throw new Error("expected a hook output object");
          }
          resolve(output);
        } catch (error) {
          reject(new Error(`Symposium ${event}: invalid hook output: ${error}`));
        }
      },
    );
    // Do not use a shell: prompts and tool inputs are untrusted text.
    child.stdin?.on("error", () => {}); // execFile reports early process exits.
    child.stdin?.end(JSON.stringify(payload));
  });
}

// Explicit SKILL.md paths bypass Pi's gitignore-aware directory scan.
// Only include Symposium-managed skills. User skills keep Pi's normal rules.
export function managedSkillPaths(cwd: string, home = homedir()): string[] {
  const parents = new Set<string>([join(home, ".agents", "skills")]);
  for (let dir = cwd; ; dir = dirname(dir)) {
    parents.add(join(dir, ".agents", "skills"));
    if (existsSync(join(dir, ".git")) || dirname(dir) === dir) break;
  }
  const paths: string[] = [];
  for (const parent of parents) {
    if (!existsSync(parent)) continue;
    for (const entry of readdirSync(parent, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const skill = join(parent, entry.name);
      if (existsSync(join(skill, ".symposium")) && existsSync(join(skill, "SKILL.md"))) {
        paths.push(join(skill, "SKILL.md"));
      }
    }
  }
  return paths.sort();
}

type HookDispatcher = (
  event: string,
  payload: Record<string, unknown>,
  cwd: string,
  signal?: AbortSignal,
) => Promise<HookOutput>;

export default function (
  pi: ExtensionAPI,
  dispatch: HookDispatcher = (event, payload, cwd, signal) =>
    runHook(event, payload, cwd, "cargo-agents", signal),
) {
  const pendingContext = new Map<string, string>();
  let warned = false;
  const warn = (ctx: ExtensionContext, event: string, error: unknown) => {
    if (ctx.signal?.aborted || warned) return;
    warned = true;
    const message = `Symposium ${event} hook failed: ${error instanceof Error ? error.message : String(error)}`;
    try {
      if (ctx.hasUI) {
        ctx.ui.notify(message, "warning");
        return;
      }
    } catch {
      // A notification failure must not block a tool either.
    }
    console.warn(message); // Keep warnings off Pi's protocol stdout.
  };
  const invoke = async (
    event: string,
    ctx: ExtensionContext,
    fields: Record<string, unknown> = {},
  ): Promise<HookOutput> => {
    try {
      return await dispatch(event, {
        cwd: ctx.cwd,
        session_id: ctx.sessionManager.getSessionId(),
        ...fields,
      }, ctx.cwd, ctx.signal);
    } catch (error) {
      warn(ctx, event, error);
      return {};
    }
  };
  const addContext = (output: HookOutput) => {
    if (output.additionalContext) {
      pi.sendMessage(
        { customType: "symposium", content: output.additionalContext, display: false },
        { deliverAs: "nextTurn" },
      );
    }
  };

  // Pi fires resources_discover after session_start, so the first prompt can
  // use the skills installed by the session-start auto-sync.
  pi.on("session_start", async (_event, ctx) => {
    pendingContext.clear();
    warned = false;
    if (!ctx.isProjectTrusted()) return;
    addContext(await invoke("session-start", ctx));
  });
  pi.on("resources_discover", (event, ctx) => ({
    skillPaths: ctx.isProjectTrusted() ? managedSkillPaths(event.cwd) : [],
  }));

  pi.on("input", async (event, ctx) => {
    if (!ctx.isProjectTrusted()) return;
    addContext(await invoke("user-prompt-submit", ctx, { prompt: event.text }));
  });

  pi.on("tool_call", async (event, ctx) => {
    pendingContext.delete(event.toolCallId);
    if (!ctx.isProjectTrusted()) return;
    try {
      const output = await invoke("pre-tool-use", ctx, {
        tool_name: event.toolName, tool_input: event.input,
      });
      if (output.decision === "deny") {
        return {
          block: true,
          reason: typeof output.additionalContext === "string" && output.additionalContext
            ? output.additionalContext : "Blocked by Symposium",
        };
      }
      if (output.updatedInput !== undefined) {
        if (!output.updatedInput || typeof output.updatedInput !== "object" || Array.isArray(output.updatedInput)) {
          throw new Error("Symposium updatedInput must be an object");
        }
        const input = event.input as Record<string, unknown>;
        for (const key of Object.keys(input)) delete input[key];
        Object.assign(input, output.updatedInput);
      }
      if (typeof output.additionalContext === "string" && output.additionalContext) {
        pendingContext.set(event.toolCallId, output.additionalContext);
      }
    } catch (error) {
      warn(ctx, "pre-tool-use", error);
    }
  });

  pi.on("tool_result", async (event, ctx) => {
    const before = pendingContext.get(event.toolCallId);
    pendingContext.delete(event.toolCallId);
    if (!ctx.isProjectTrusted()) return;
    const output = await invoke("post-tool-use", ctx, {
      tool_name: event.toolName,
      tool_input: event.input,
      tool_response: {
        content: event.content,
        details: event.details,
        structuredContent: event.structuredContent,
        isError: event.isError,
      },
    });
    const context = [before, output.additionalContext].filter(
      (text): text is string => typeof text === "string" && text.length > 0,
    );
    if (context.length) {
      return {
        content: [...event.content, ...context.map((text) => ({ type: "text" as const, text }))],
        structuredContent: event.structuredContent,
      };
    }
  });

  pi.on("agent_end", async (_event, ctx) => {
    pendingContext.clear();
    if (!ctx.isProjectTrusted()) return;
    // No triggerTurn: a Stop hook must not start another agent turn.
    addContext(await invoke("stop", ctx));
  });
  pi.on("session_shutdown", () => { pendingContext.clear(); });
}
